language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
xcode_workspace: AutoImporter/AutoImporter.xcworkspace
xcode_scheme: Auto-Importer